"use client";
// import type { Metadata } from "next";
import "./globals.scss";
import { MsalProvider } from "@azure/msal-react";
import { PublicClientApplication } from "@azure/msal-browser";
import { msalConfig } from "../../msalConfig";

const msalInstance = new PublicClientApplication(msalConfig);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MsalProvider instance={msalInstance}>
      <html lang="pt-br">
        <body>
          <div>{children}</div>
        </body>
      </html>
    </MsalProvider>
  );
}
